version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn compile
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package -DskipTests
artifacts:
  files:
    - target/cal-notify-1.0.13-SNAPSHOT.jar
	